#!/bin/bash

echo "# Install all update."
dpkg --configure -a &&  apt update &&   apt upgrade -y &&
apt clean -y &&  rm -rf /var/lib/apt/lists/* &&  apt update -y &&  apt full-upgrade -y &&  apt autoremove -y &&  apt autoclean &&  apt purge ~c -y
echo ""
echo ""
echo ""
echo "# Disable ping and IPv6."
echo "blacklist ipv6 " > /etc/modprobe.d/blacklist-ipv6.conf
update-initramfs -u
if grep --color 'net.ipv4.icmp_echo_ignore_all=1' /etc/sysctl.conf; then
   echo "Ping already blocked."
else
   echo "Ping will be blocked now. It's OK."
    echo "net.ipv4.icmp_echo_ignore_all=1" >> /etc/sysctl.conf
fi
if grep --color 'net.ipv6.conf.all.disable_ipv6 = 1' /etc/sysctl.conf; then
   echo "IPv6 already blocked."
else
   echo "IPv6 will be blocked now. It's OK."
    echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
fi
   sysctl -p
echo ""
echo ""
echo ""
echo  -e "\033[31m# Change standard SSH port (22) to non-standard port (24940, for example...).\033[0m"
read  -p  "Press ENTER..."
grep --color '#Port ' /etc/ssh/sshd_config
sh -c "sed -i 's/#Port /Port /' /etc/ssh/sshd_config"
grep --color 'Port ' /etc/ssh/sshd_config; read -p "Type current SSH port, for checking: " search
read -p "REMEMBER or SAVE it! Type new (desired) SSH port: " replace
sh -c "sed -i 's/Port $search/Port $replace/' /etc/ssh/sshd_config"
echo ""
echo ""
echo ""
systemctl restart ssh
systemctl status ssh
echo ""
echo ""
echo ""
echo "# Install mc, curl, wget, htop, unattended-upgrades, apt-listchanges, fail2ban."
apt install rsyslog mc curl wget unzip p7zip-full htop apt-listchanges bsd-mailx iptables fail2ban dos2unix locales screen dnsutils -y
echo ""
echo ""
echo ""
echo "Set UTF-8 locales."
sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen
sed -i 's/^# *\(ru_RU.UTF-8\)/\1/' /etc/locale.gen
locale-gen
cat <<EOF |  tee /etc/default/locale
#  File generated by update-locale
LANG="ru_RU.UTF-8"
#LANG="en_US.UTF-8"
EOF
echo ""
echo ""
echo ""
sysctl --system
systemctl enable fail2ban.service
sh -c "sed -i 's/\s\s*/ /g' /etc/fail2ban/jail.conf"
sh -c "sed -i 's/bantime = 10m/bantime = 720m/' /etc/fail2ban/jail.conf"
sh -c "sed -i 's/findtime = 10m/findtime = 60m/' /etc/fail2ban/jail.conf"
sh -c "sed -i 's/maxretry = 5/maxretry = 3/' /etc/fail2ban/jail.conf"
if grep --color '#allowipv6 = auto' /etc/sysctl.conf; then
   sh -c "sed -i 's/#allowipv6 = auto/allowipv6 = auto/" /etc/fail2ban/fail2ban.conf
else
   echo "allowipv6 = AUTO now. It's OK."
fi
echo '[DEFAULT]' > /etc/fail2ban/jail.local
echo 'ignoreip = 45.86.86.195 46.29.239.23 45.38.143.206' >> /etc/fail2ban/jail.local
cat /etc/fail2ban/jail.local
systemctl restart fail2ban.service
systemctl status fail2ban.service
echo -e "\033[31mDon't forget to add the new SSH port in the your SSH client!\033[0m"
grep --color 'Port ' /etc/ssh/sshd_config
read  -p  "Press ENTER..."
echo ""
echo ""
echo ""
cd /root
systemctl --failed
echo ""
echo ""
echo ""
echo -e "\033[31mLast update.\033[0m"
read  -p  "Press ENTER..."
apt clean -y &&  rm -rf /var/lib/apt/lists/* &&  apt update -y &&  apt full-upgrade -y &&  apt autoremove -y &&  apt autoclean &&  apt purge ~c -y
echo ""
echo ""
echo ""
echo -e "\033[31mChange ROOT PASSWORD.\033[0m"
read  -p  "Press ENTER if you ready..."
passwd
echo ""
echo ""
echo ""
read  -p  "Press ENTER for reboot..."
echo ""
echo ""
echo ""
echo "REBOOT"
echo ""
echo ""
echo ""
reboot 

