#!/bin/bash

echo "# Install all update."
dpkg --configure -a
apt clean -y && rm -rf /var/lib/apt/lists/* && apt update -y && apt full-upgrade -y && apt autoremove -y && apt autoclean && apt purge ~c -y
echo ""
echo ""
echo ""
echo -e "\033[31m# Change PRETTY hostname!!!\033[0m"
read -n1 -s -r -p "Press any key..."; echo
read -p "Type new PRETTY hostname here: " newhostname
hostnamectl set-hostname "$newhostname" --pretty
echo ""
echo ""
echo ""
echo "# Disable ping and IPv6."
echo "blacklist ipv6" > /etc/modprobe.d/blacklist-ipv6.conf
update-initramfs -u
if grep --color 'net.ipv4.icmp_echo_ignore_all=1' /etc/sysctl.conf; then
   echo "Ping already blocked."
else
   echo "Ping will be blocked now. It's OK."
   echo "net.ipv4.icmp_echo_ignore_all=1" >> /etc/sysctl.conf
fi
if grep --color 'net.ipv6.conf.all.disable_ipv6 = 1' /etc/sysctl.conf; then
   echo "IPv6 already blocked."
else
   echo "IPv6 will be blocked now. It's OK."
   echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
fi
sysctl -p
echo ""
echo ""
echo ""
echo -e "\033[31m# Configure SSH to listen on ports 22 and 24940.\033[0m"
read -n1 -s -r -p "Press any key..."; echo
# Удаляем все существующие директивы Port и добавляем две нужные
sed -i '/^Port /d' /etc/ssh/sshd_config
echo "Port 22" >> /etc/ssh/sshd_config
echo "Port 24940" >> /etc/ssh/sshd_config
# Разрешаем root-доступ только по ключам
sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin without-password/' /etc/ssh/sshd_config
sed -i 's/^#\?PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
#systemctl restart ssh
#systemctl status ssh
echo ""
echo ""
echo ""
echo "# Install mc, curl, wget, htop, unattended-upgrades, apt-listchanges, fail2ban, ufw."
apt install sudo ufw cron rsyslog mc curl wget unzip p7zip-full htop unattended-upgrades apt-listchanges bsd-mailx iptables fail2ban dos2unix locales screen dnsutils openssl gpg -y &&

# Настройка unattended-upgrades (автоматические обновления безопасности)
echo ""
echo "# Configuring unattended-upgrades..."
echo ""

# Основные параметры периодичности
cat > /etc/apt/apt.conf.d/20auto-upgrades <<EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "1";
APT::Periodic::Unattended-Upgrade "1";
EOF

# Разрешаем только обновления безопасности (и ESM, если есть)
cat > /etc/apt/apt.conf.d/50unattended-upgrades <<EOF
Unattended-Upgrade::Allowed-Origins {
    "\${distro_id}:\${distro_codename}-security";
    "\${distro_id}ESMApps:\${distro_codename}-apps-security";
    "\${distro_id}ESM:\${distro_codename}-infra-security";
};
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Mail "root";
Unattended-Upgrade::MailOnlyOnError "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Automatic-Reboot-Time "00:01";
EOF

# Включаем и запускаем службу (хотя она уже может быть активна)
systemctl enable unattended-upgrades
systemctl restart unattended-upgrades

echo "Unattended-upgrades configured."
echo ""

if grep -q "sudo mc" ~/.profile; then
   echo "Midnight Commander exists!"
else
   echo "screen -r" >> ~/.profile
   echo "sudo mc" >> ~/.profile
fi
echo ""
echo ""
echo ""
echo "Set UTF-8 locales."
sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen
sed -i 's/^# *\(ru_RU.UTF-8\)/\1/' /etc/locale.gen
locale-gen
cat <<EOF | tee /etc/default/locale
#  File generated by update-locale
LANG="ru_RU.UTF-8"
#LANG="en_US.UTF-8"
EOF
echo ""
echo ""
echo ""
sysctl --system

# Настройка Fail2ban
systemctl enable fail2ban.service
sed -i 's/\s\s*/ /g' /etc/fail2ban/jail.conf
sed -i 's/bantime = 10m/bantime = 1440m/' /etc/fail2ban/jail.conf
sed -i 's/findtime = 10m/findtime = 90m/' /etc/fail2ban/jail.conf
sed -i 's/maxretry = 5/maxretry = 2/' /etc/fail2ban/jail.conf
if grep --color '#allowipv6 = auto' /etc/fail2ban/fail2ban.conf; then
   sed -i 's/#allowipv6 = auto/allowipv6 = auto/' /etc/fail2ban/fail2ban.conf
else
   echo "allowipv6 = AUTO now. It's OK."
fi
# Создаём jail.local с ignoreip и секцией для sshd с обоими портами
cat > /etc/fail2ban/jail.local <<EOF
[DEFAULT]
ignoreip = 176.56.1.165 95.78.162.177 45.86.86.195 46.29.239.23 45.38.143.206 193.233.203.194 194.58.68.23

[sshd]
enabled = true
port = 22,24940
EOF
systemctl restart fail2ban.service
systemctl status fail2ban.service
echo -e "\033[31mDon't forget to add the new SSH port (24940) in the client!\033[0m"
grep --color 'Port ' /etc/ssh/sshd_config
read -n1 -s -r -p "Press any key..."; echo
echo ""
echo ""
echo ""
wget -O setup.7z https://raw.githubusercontent.com/hummer74/new-server/main/setup.7z
echo -e "\033[31m# Copy /root/.dir from archive.pass.\033[0m"
read -n1 -s -r -p "Press any key..."; echo
7za x setup.7z -aoa
rm setup.7z
echo "Fix directory permissions"
chmod 700 ~/.config/htop
chmod 700 ~/.config/mc
chmod 700 ~/.ssh
echo ""
echo "Fix all key permissions"
chmod 600 ~/.ssh/*
chmod 644 ~/.ssh/*.pub
echo ""
echo "Fix special files permissions"
chmod 644 ~/.ssh/authorized_keys
chmod 644 ~/.ssh/known_hosts
chmod 644 ~/.ssh/config
echo ""
chmod +x ~/auto-update.sh

# WARNING: Ensure ~/.ssh/passwd.txt contains line "username:password"
if [ -f ~/.ssh/passwd.txt ]; then
   chpasswd < ~/.ssh/passwd.txt
else
   echo "~/.ssh/passwd.txt not found, password not changed."
fi
echo ""
echo ""
echo ""
echo -e "\033[31m# Add ordinary user OPOSSUM with PASSWORD!\033[0m"
userdel -r opossum 2>/dev/null
if [ $(id -u) -eq 0 ]; then
   read -s -p "Enter password : " password
   echo
   egrep "opossum" /etc/passwd >/dev/null
   if [ $? -eq 0 ]; then
      echo "opossum exists!"
   else
      pass=$(openssl passwd -6 "$password")
      useradd -m -p "$pass" "opossum"
      if [ $? -eq 0 ]; then
         echo "User opossum has been added to system!"
         usermod -a -G sudo opossum
      else
         echo "Failed to add a user!"
      fi
   fi
else
   echo "Only root may add a user to the system."
fi
if [ -d /home/opossum ]; then
   cd /home/opossum
   wget -O opossum.7z https://raw.githubusercontent.com/hummer74/new-server/main/opossum.7z
   wget -O opossum.sh https://raw.githubusercontent.com/hummer74/new-server/main/opossum.sh
   chmod +x opossum.sh
   cd /root
else
   echo "Home directory for opossum not found, skipping downloads."
fi
echo ""
echo ""
echo ""
systemctl --failed
echo ""
systemctl reset-failed
# Автоматическое создание файла с pretty hostname
safe_name=$(echo "$newhostname" | tr ' ' '_' | tr -cd '[:alnum:]_-')
touch "zzz-$safe_name"
echo ""
echo ""
echo ""
echo ""
echo ""

# Настройка UFW (файрвол) – добавляем правила и спрашиваем о включении
echo "Configuring UFW firewall..."
# Добавляем правила для SSH портов
ufw allow 22/tcp
ufw allow 24940/tcp
echo "SSH ports 22 and 24940 are allowed."
# Интерактивный запрос на включение
read -p "Do you want to enable UFW now? (y/N): " enable_ufw
if [[ "$enable_ufw" =~ ^[Yy]$ ]]; then
    echo "Enabling UFW..."
    ufw --force enable
    echo "UFW is now enabled and active."
    ufw status verbose
else
    echo "UFW rules have been added but the firewall is not enabled."
    echo "You can enable it later with: sudo ufw enable"
fi

# ===== Additional services block =====
echo -e "\033[31mDo you want to install additional services (Xray, 3X-UI, WireGuard, OpenVPN)?\033[0m"
read -p "Proceed? (Y/N. Default [N]): " install_extra
if [[ "$install_extra" =~ ^[yY]+$ ]]; then
    echo "# Ok. Proceeding with additional services installation."
    apt clean -y && rm -rf /var/lib/apt/lists/* && apt update -y && apt full-upgrade -y && apt autoremove -y && apt autoclean && apt purge ~c -y
    echo ""
    # Xray
    echo "Install VLESS, Xray-Reality."
    read -p "Do you want to proceed? (Y/N. Default [N]): " yn1
    if [[ "$yn1" =~ ^[yY]+$ ]]; then
        echo "# Ok. Install VLESS, Xray-Reality."
        read -n1 -s -r -p "Press any key..."; echo
        bash <(curl -Ls https://github.com/XTLS/Xray-install/raw/main/install-release.sh)
    else
        yn1='N'
        echo "Ok. Skip Xray."
    fi
    echo ""
    echo ""
    # 3X-UI
    echo "# Install 3X-UI."
    echo -e "\033[31m# Opossum, StandardPass, Port: 33900\033[0m."
    read -p "Do you want to proceed? (Y/N. Default [N]): " yn1
    if [[ "$yn1" =~ ^[yY]+$ ]]; then
        echo "# Ok. Install 3X-UI."
        read -n1 -s -r -p "Press any key..."; echo
        bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh)
    else
        yn1='N'
        echo "Ok. Skip 3X-UI."
    fi
    echo ""
    echo ""
    # WireGuard
    echo -e "# Install WireGuard, port \033[31m33901\033[0m."
    read -p "Do you want to proceed? (Y/N. Default [N]): " yn1
    if [[ "$yn1" =~ ^[yY]+$ ]]; then
        echo "# Ok. Install WireGuard."
        read -n1 -s -r -p "Press any key..."; echo
        bash <(curl -Ls https://raw.githubusercontent.com/angristan/wireguard-install/master/wireguard-install.sh)
        read -p "Enter WireGuard interface name (default wg0): " wg_iface
        wg_iface=${wg_iface:-wg0}
        sysctl --system
        systemctl restart wg-quick@$wg_iface
        systemctl status wg-quick@$wg_iface
    else
        yn1='N'
        echo "Ok. Skip WireGuard."
    fi
    echo ""
    echo ""
    # OpenVPN
    echo -e "# Install OpenVPN, port \033[31m33902\033[0m."
    read -p "Do you want to proceed? (Y/N. Default [N]): " yn1
    if [[ "$yn1" =~ ^[yY]+$ ]]; then
        echo "# Ok. Install OpenVPN."
        read -n1 -s -r -p "Press any key..."; echo
        bash <(curl -Ls https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh)
    else
        yn1='N'
        echo "Ok. Skip OpenVPN."
    fi
    echo ""
    echo ""
else
    echo "Ok. No additional services will be installed."
fi
# ===== End of additional services block =====
echo ""

# Устанавливаем новые задания cron, полностью заменяя текущий crontab
crontab - <<EOF
@reboot		date >> /root/reboot.log
* * * * *	systemctl reset-failed
0 1 * * *	/root/auto-update.sh
0 0 1 * *	date > /root/reboot.log
EOF

echo "Crontab успешно обновлён."
echo ""
echo ""
echo ""
echo -e "\033[31mLast update.\033[0m"
read -n1 -s -r -p "Press any key..."; echo
apt clean -y && rm -rf /var/lib/apt/lists/* && apt update -y && apt full-upgrade -y && apt autoremove -y && apt autoclean && apt purge ~c -y
read -n1 -s -r -p "Press any key for reboot..."; echo
echo ""
echo ""
echo ""
echo "REBOOT"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
reboot now