#!/bin/bash

RED='\033[0;31m[1m''    # ${RED}
echo -en "${RED} Set UTF-8 locales."
tput sgr0

echo "Set UTF-8 locales."
sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen
sed -i 's/^# *\(ru_RU.UTF-8\)/\1/' /etc/locale.gen
locale-gen
sudo cat <<EOF | sudo tee /etc/default/locale
#  File generated by update-locale
LANG="ru_RU.UTF-8"
#LANG="en_US.UTF-8"
EOF
echo ""
echo ""
echo "Bye!"
